### PR TITLE
Fix #6: Move async dependency into package-utils-install-async function

### LINKED ISSUE #6: Consider moving (require 'async) into only the functions that need it
My use case for upgrading packages automatically is calling Emacs from a shell script, so I don't need any of the functionality of the `async` library. It would be nice to have its require statement moved into the single function which needs `async`, so that I don't have to install that library.

### PR DESCRIPTION
**Pull request by mwolson**

### CODE REVIEW

**Comment by Silex** [comment]
Well, that just moves the `require` but the package itself still depends on async (see https://github.com/Silex/package-utils/blob/master/package-utils.el#L7)

That said, it's been a while now that I'm not happy about the async dependency.

I think what would be nice is, *if* async is installed then maybe we could have `package-utils-async.el` with some helper functions. Do you agree?

**Comment by mwolson** [comment]
Up to you. I suppose it depends on how many further async functions are
planned to be added in the future.

**Comment by Silex** [comment]
Well, the async functions were not added by me. Originally there was two of them (`package-list-package-async`), but I removed it because in recent emacs `package-list-package` is async already.

**Comment by mwolson** [comment]
I think I'll abandon the PR for now, since it was possible to just do `(mapc #'package-install package-selected-packages)` in my bootstrap script to bring in both the package itself and the async dependency, and then `(require 'package-utils)`.

**Comment by Silex** [comment]
Alright, I'll probably do as I said anyway and remove the async dependency, like projectile does for helm.

**Comment by Silex** [comment]
Actually, your PR is mergeable right now and I'll remove the async dependency later.

**Pull request merged**
